# Generated by Django 5.2.8 on 2026-08-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='github_url',
        ),
        migrations.AddField(
            model_name='music',
            name='fileurl',
            field=models.TextField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
