# Generated by Django 5.2.8 on 2026-08-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_music_github_url_music_fileurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.AddField(
            model_name='music',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.artist'),
        ),
    ]
