# Generated by Django 5.2.8 on 2025-12-11 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0023_lifeprincipletopic_lifeprinciple_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('statement_text', models.TextField()),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('inprogress', 'In-Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatementOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_description', models.TextField()),
                ('decision', models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree')], max_length=20)),
                ('advice_from', models.CharField(blank=True, max_length=255, null=True)),
                ('advice_reason', models.TextField(blank=True, null=True)),
                ('cancelled_principles', models.ManyToManyField(blank=True, to='tracker.lifeprinciple')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='statement.statement')),
            ],
        ),
    ]
