# Generated by Django 5.2.8 on 2025-12-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementoption',
            name='decision',
            field=models.CharField(blank=True, choices=[('agree', 'Agree'), ('disagree', 'Disagree')], max_length=20, null=True),
        ),
    ]
