# Generated by Django 5.2.8 on 2025-12-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0002_alter_statementoption_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementoption',
            name='advice_is_link',
            field=models.BooleanField(default=False),
        ),
    ]
