# Generated by Django 5.2.8 on 2026-06-03 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0003_statementoption_advice_is_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementoption',
            name='statement',
        ),
        migrations.RemoveField(
            model_name='statementoption',
            name='cancelled_principles',
        ),
        migrations.DeleteModel(
            name='Statement',
        ),
        migrations.DeleteModel(
            name='StatementOption',
        ),
    ]
