# Generated by Django 5.2.8 on 2026-06-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CURRENT', 'Current'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
    ]
