# Generated by Django 5.2.8 on 2026-06-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0006_statement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CURRENT', 'Current'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20),
        ),
    ]
