# Generated by Django 5.2.8 on 2026-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_lunaprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunaImagePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Describe when this image should be used.')),
                ('image_name', models.CharField(help_text='Image id from google drive.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Luna Image Prompt',
                'verbose_name_plural': 'Luna Image Prompts',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
