# Generated by Django 5.2.8 on 2026-09-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_lunaimageprompt_message_image_alt_message_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunaimageprompt',
            name='image_name',
        ),
        migrations.AddField(
            model_name='lunaimageprompt',
            name='image_google_id',
            field=models.CharField(default=None, help_text='Google Drive image file ID.', max_length=255),
            preserve_default=False,
        ),
    ]
