# Generated by Django 5.2.8 on 2026-09-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_lunaimageprompt_image_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='image_name',
            new_name='image_google_id',
        ),
    ]
