# Generated by Django 5.2.8 on 2026-09-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_image_name_message_image_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image_google_id',
        ),
    ]
