# Generated by Django 5.2.8 on 2025-12-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
