# Generated by Django 5.2.8 on 2025-12-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_phase',
            field=models.BooleanField(default=True),
        ),
    ]
