# Generated by Django 5.2.8 on 2025-12-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_word_is_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='is_phase',
            field=models.BooleanField(default=False),
        ),
    ]
