# Generated by Django 5.2.8 on 2026-04-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='personal',
            field=models.BooleanField(default=False),
        ),
    ]
