# Generated by Django 5.2.8 on 2025-12-24 16:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tracker', '0001_initial'), ('tracker', '0002_task_task_type'), ('tracker', '0003_alter_task_task_type'), ('tracker', '0004_task_target_date'), ('tracker', '0005_alter_update_date'), ('tracker', '0006_alter_task_target_date_alter_update_date'), ('tracker', '0007_alter_task_completed_date_alter_task_started_date_and_more'), ('tracker', '0008_remove_task_sprint_delete_sprint'), ('tracker', '0009_tasktype_alter_task_task_type'), ('tracker', '0010_alter_task_task_type'), ('tracker', '0011_lifeprinciple'), ('tracker', '0012_filespec_document'), ('tracker', '0013_remove_document_filespec_document_filetype_and_more'), ('tracker', '0014_task_is_private'), ('tracker', '0015_update_is_check_box_update_is_completed'), ('tracker', '0016_alter_update_date'), ('tracker', '0017_updatetemplate'), ('tracker', '0018_task_created_date'), ('tracker', '0019_alter_task_started_date'), ('tracker', '0020_alter_task_created_date'), ('tracker', '0021_task_is_hold'), ('tracker', '0022_task_is_bookmark'), ('tracker', '0023_lifeprincipletopic_lifeprinciple_topic'), ('tracker', '0024_update_date_to_remind_update_is_monthly_reminder'), ('tracker', '0025_alter_task_status'), ('tracker', '0026_update_status'), ('tracker', '0027_remove_task_is_hold_remove_update_is_completed_and_more'), ('tracker', '0028_task_is_important'), ('tracker', '0029_task_is_template'), ('tracker', '0030_update_reminder_type'), ('tracker', '0031_remove_update_is_monthly_reminder'), ('tracker', '0032_alter_update_reminder_type')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('InProgress', 'In Progress'), ('Completed', 'Completed')], default='Opened', max_length=20)),
                ('started_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('Official', 'Official'), ('Personal', 'Personal')], default='Personal', max_length=20)),
                ('target_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='tracker.task')),
                ('is_check_box', models.BooleanField(default=False)),
                ('date_to_remind', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Opened', max_length=20)),
                ('reminder_type', models.CharField(blank=True, choices=[('Days', 'Days'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tracker.tasktype'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('fileurl', models.CharField(max_length=255)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tracker.update')),
                ('filetype', models.CharField(default=None, editable=False, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UpdateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=None),
        ),
        migrations.AddField(
            model_name='task',
            name='is_bookmark',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LifePrincipleTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifePrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle', models.TextField()),
                ('meaning', models.TextField()),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='principle_topic', to='tracker.lifeprincipletopic')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Hold', 'Hold')], default='Opened', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
