# Generated by Django 5.2.8 on 2025-11-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Official', 'Official'), ('Personal', 'Personal')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
