# Generated by Django 5.2.8 on 2025-11-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Official', 'Official'), ('Personal', 'Personal')], default='Personal', max_length=20),
        ),
    ]
