# Generated by Django 5.2.8 on 2025-11-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
