# Generated by Django 5.2.8 on 2025-11-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_task_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
