# Generated by Django 5.2.8 on 2025-11-08 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
