# Generated by Django 5.2.8 on 2025-11-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_task_completed_date_alter_task_started_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sprint',
        ),
        migrations.DeleteModel(
            name='Sprint',
        ),
    ]
