# Generated by Django 5.2.8 on 2025-11-08 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_tasktype_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tracker.tasktype'),
            preserve_default=False,
        ),
    ]
