# Generated by Django 5.2.8 on 2025-11-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_task_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifePrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle', models.TextField()),
                ('meaning', models.TextField()),
            ],
        ),
    ]
