# Generated by Django 5.2.8 on 2025-11-09 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_lifeprinciple'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('video', 'Video'), ('other', 'Other')], max_length=20)),
                ('file_extension', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('fileurl', models.URLField()),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tracker.update')),
                ('filespec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.filespec')),
            ],
        ),
    ]
