# Generated by Django 5.2.8 on 2025-11-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_filespec_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='filespec',
        ),
        migrations.AddField(
            model_name='document',
            name='filetype',
            field=models.CharField(default=None, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='fileurl',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='FileSpec',
        ),
    ]
