# Generated by Django 5.2.8 on 2025-11-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_remove_document_filespec_document_filetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
