# Generated by Django 5.2.8 on 2025-11-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_task_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='is_check_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='update',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
