# Generated by Django 5.2.8 on 2025-11-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_updatetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
