# Generated by Django 5.2.8 on 2025-11-28 04:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_task_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
