# Generated by Django 5.2.8 on 2025-11-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_alter_task_started_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
