# Generated by Django 5.2.8 on 2025-11-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_alter_task_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_hold',
            field=models.BooleanField(default=False),
        ),
    ]
