# Generated by Django 5.2.8 on 2025-11-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_task_is_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_bookmark',
            field=models.BooleanField(default=False),
        ),
    ]
