# Generated by Django 5.2.8 on 2025-12-07 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_task_is_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifePrincipleTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lifeprinciple',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='principle_topic', to='tracker.lifeprincipletopic'),
        ),
    ]
