# Generated by Django 5.2.8 on 2025-12-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_lifeprincipletopic_lifeprinciple_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='date_to_remind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='is_monthly_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
