# Generated by Django 5.2.8 on 2025-12-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Opened', max_length=20),
        ),
    ]
