# Generated by Django 5.2.8 on 2025-12-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_update_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_hold',
        ),
        migrations.RemoveField(
            model_name='update',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Hold', 'Hold')], default='Opened', max_length=20),
        ),
    ]
