# Generated by Django 5.2.8 on 2025-12-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_task_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='reminder_type',
            field=models.CharField(blank=True, choices=[('Opened', 'Opened'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20, null=True),
        ),
    ]
