# Generated by Django 5.2.8 on 2025-12-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_update_reminder_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='is_monthly_reminder',
        ),
    ]
