# Generated by Django 5.2.8 on 2025-12-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_remove_update_is_monthly_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='reminder_type',
            field=models.CharField(blank=True, choices=[('Days', 'Days'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20, null=True),
        ),
    ]
