# Generated by Django 5.2.8 on 2025-12-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial_squashed_0032_alter_update_reminder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='can_store_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='filetype',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
