# Generated by Django 5.2.8 on 2026-02-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_update_can_store_reminder_alter_document_filetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='filetype',
        ),
    ]
