# Generated by Django 5.2.8 on 2026-02-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_remove_document_filetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('extensions', models.TextField(help_text='Comma-separated extensions like .pdf,.docx,.jpg')),
                ('preview_html', models.TextField(help_text='\n            Use {{ url }} for file URL\n            Use {{ filename }} for file name\n        ')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='filetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.filetype'),
        ),
    ]
