# Generated by Django 5.2.8 on 2026-02-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_filetype_document_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetype',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Bootstrap icon class, e.g. bi-file-earmark-pdf-fill', max_length=100),
        ),
        migrations.AddField(
            model_name='filetype',
            name='show_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
