# Generated by Django 5.2.8 on 2026-02-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_filetype_icon_class_filetype_show_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetype',
            name='show_thumbnail',
        ),
        migrations.AlterField(
            model_name='filetype',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Bootstrap icon class. Leave empty to show thumbnail.', max_length=100),
        ),
    ]
