# Generated by Django 5.2.8 on 2026-02-19 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0038_alter_task_started_date_alter_task_target_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_web_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 2, 19, 16, 19, 3, 522390, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 2, 19, 16, 19, 3, 553004, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 2, 19, 16, 19, 3, 553586, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
