# Generated by Django 5.2.8 on 2026-02-21 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0040_alter_task_started_date_alter_task_target_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god_name', models.CharField(max_length=100)),
                ('god_photo_url', models.URLField()),
                ('god_audio_url', models.URLField()),
                ('god_icon_url', models.URLField()),
                ('prayer', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 2, 21, 17, 30, 43, 493932, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 2, 21, 17, 30, 43, 508145, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 2, 21, 17, 30, 43, 508721, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
