# Generated by Django 5.2.8 on 2026-03-15 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0041_prayer_alter_task_started_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 15, 3, 52, 37, 730268, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 15, 3, 52, 37, 760083, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 15, 3, 52, 37, 760917, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
