# Generated by Django 5.2.8 on 2026-03-15 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0042_update_time_alter_task_started_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='update',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 15, 3, 59, 49, 46009, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 15, 3, 59, 49, 52035, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 15, 3, 59, 49, 52579, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
