# Generated by Django 5.2.8 on 2026-03-18 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0047_alter_task_started_date_alter_task_target_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='god_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 18, 4, 18, 7, 622566, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 18, 4, 18, 7, 629070, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 18, 4, 18, 7, 629933, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
