# Generated by Django 5.2.8 on 2026-05-08 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0060_alter_task_started_date_alter_task_target_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='auto_reminder_handle',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 5, 8, 23, 57, 54, 465821, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 5, 8, 23, 57, 54, 472415, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 5, 8, 23, 57, 54, 473001, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
