# Generated by Django 5.2.8 on 2026-05-29 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0062_notification_alter_task_started_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 5, 29, 12, 39, 2, 814497, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 5, 29, 12, 39, 2, 827693, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 5, 29, 12, 39, 2, 828303, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
