# Generated by Django 5.2.8 on 2026-06-25 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0071_alter_task_started_date_alter_task_target_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 6, 25, 12, 35, 19, 108661, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 6, 25, 12, 35, 19, 137006, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 6, 25, 12, 35, 19, 137723, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
