# Generated by Django 5.2.8 on 2026-06-25 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0073_alter_task_started_date_alter_task_target_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 6, 25, 13, 13, 46, 429203, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 6, 25, 13, 13, 46, 435389, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 6, 25, 13, 13, 46, 435970, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
