# Generated by Django 5.2.8 on 2026-06-25 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0074_update_name_alter_task_started_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 6, 25, 13, 22, 58, 761432, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 6, 25, 13, 22, 58, 767137, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 6, 25, 13, 22, 58, 767664, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
