# Generated by Django 5.2.8 on 2026-08-02 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0082_symbol_alter_task_started_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symbol',
            options={},
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='display_order',
        ),
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 8, 2, 10, 23, 33, 559588, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 8, 2, 10, 23, 33, 565476, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 8, 2, 10, 23, 33, 566024, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
