# Generated by Django 5.2.8 on 2026-08-19 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0086_alter_task_started_date_alter_task_target_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 8, 19, 6, 43, 2, 282526, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 8, 19, 6, 43, 2, 288448, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 8, 19, 6, 43, 2, 289011, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
