# Generated by Django 5.2.8 on 2026-09-19 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0095_alter_task_started_date_alter_task_target_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 9, 19, 8, 38, 2, 267261, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 9, 19, 8, 38, 2, 274112, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 9, 19, 8, 38, 2, 274746, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
