# Generated by Django 5.2.8 on 2026-09-23 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0096_alter_task_started_date_alter_task_target_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='clear_time_on_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 9, 23, 8, 45, 18, 466572, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 9, 23, 8, 45, 18, 516922, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 9, 23, 8, 45, 18, 518049, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
